In [4]:
import numpy as np

In [5]:
a=np.array([1,3,4,5])
a

array([1, 3, 4, 5])

In [7]:
nap=np.array([(2,4,5,6,4,5),(2,8,9,0,3),(20,4,7,8,0)])
nap

array([(2, 4, 5, 6, 4, 5), (2, 8, 9, 0, 3), (20, 4, 7, 8, 0)],
      dtype=object)

In [9]:
gu=np.zeros((3,6))
gu

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
y=np.ones((1,3,4), dtype=np.int16)
y

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [13]:
d=np.arange(10,5,6)
d

array([], dtype=int64)

In [14]:
p=np.linspace(2,7,8,4,6)
p

(array([2.        , 2.71428571, 3.42857143, 4.14285714, 4.85714286,
        5.57142857, 6.28571429, 7.        ]), 0.7142857142857143)

In [17]:
e=np.full((2,5),7)
e

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [19]:
#creating two by two matrix
t=np.eye(2)
t

array([[1., 0.],
       [0., 1.]])

In [20]:
ti=np.eye(5)
ti

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
#creating a matrix with random  numbers
rep=np.random.random((1,2))
rep

array([[0.81412769, 0.51078189]])

In [26]:
w=np.random.random((2,9))
w

array([[0.1620896 , 0.50218666, 0.1533489 , 0.16199741, 0.9678347 ,
        0.92873106, 0.07583748, 0.00443547, 0.66890929],
       [0.6814548 , 0.33577617, 0.36662643, 0.07290834, 0.34599665,
        0.46274039, 0.6396927 , 0.28897826, 0.71290919]])

In [32]:
#creating an empty array
ty=np.empty((2,3))
ty

array([[1.02941932e-071, 4.57842046e-071, 4.46470459e-086],
       [3.35558946e-143, 6.01433264e+175, 6.93885958e+218]])

In [33]:
#array dimenstion
ty.shape

(2, 3)

In [34]:
#array length
len(ty)

2

In [35]:
#dimenstion of the array
ty.ndim

2

In [36]:
#type of the data type
ty.dtype

dtype('float64')

In [37]:
ty.dtype.name

'float64'

In [38]:
#conerting  an array to naother datatype
ty.astype(int)

array([[                   0,                    0,                    0],
       [                   0, -9223372036854775808, -9223372036854775808]])

In [39]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [42]:
np.exp(ty)

/home/karimi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


array([[ 1.,  1.,  1.],
       [ 1., inf, inf]])

In [43]:
np.sqrt(ty)

array([[3.20845651e-036, 6.76640263e-036, 2.11298476e-043],
       [5.79274500e-072, 7.75521285e+087, 2.63417152e+109]])

In [44]:
np.cos(ty)

array([[ 1.        ,  1.        ,  1.        ],
       [ 1.        , -0.98019869, -0.99745437]])

In [45]:
np.sin(ty)

array([[ 1.02941932e-071,  4.57842046e-071,  4.46470459e-086],
       [ 3.35558946e-143, -1.98016502e-001, -7.13077013e-002]])

In [49]:
ty.sum()

6.938859583927063e+218

In [50]:
ty.mean()

1.156476597321177e+218

In [56]:
np.copy(ty)

array([[1.02941932e-071, 4.57842046e-071, 4.46470459e-086],
       [3.35558946e-143, 6.01433264e+175, 6.93885958e+218]])

In [57]:
o=np.copy(ty)
o

array([[1.02941932e-071, 4.57842046e-071, 4.46470459e-086],
       [3.35558946e-143, 6.01433264e+175, 6.93885958e+218]])

In [63]:
pin=w.sort()
pin


In [64]:
pin

In [67]:
pina=w.sort(axis=0)
pina

In [68]:
a=np.array((1,4,5,6))
a

array([1, 4, 5, 6])

In [70]:
b= np.array([(1,2,3,4,),(1,6,7,8)])
b

array([[1, 2, 3, 4],
       [1, 6, 7, 8]])

In [76]:
#create a mesh grid
grabe=np.mgrid[5:10,4:8]
grabe

array([[[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]],

       [[4, 5, 6, 7],
        [4, 5, 6, 7],
        [4, 5, 6, 7],
        [4, 5, 6, 7],
        [4, 5, 6, 7]]])

In [77]:
#create an open grid
np.ogrid[0:3,5:8]

[array([[0],
        [1],
        [2]]), array([[5, 6, 7]])]

In [80]:
np.transpose(grabe)

array([[[5, 4],
        [6, 4],
        [7, 4],
        [8, 4],
        [9, 4]],

       [[5, 5],
        [6, 5],
        [7, 5],
        [8, 5],
        [9, 5]],

       [[5, 6],
        [6, 6],
        [7, 6],
        [8, 6],
        [9, 6]],

       [[5, 7],
        [6, 7],
        [7, 7],
        [8, 7],
        [9, 7]]])

In [82]:
b

array([[1, 2, 3, 4],
       [1, 6, 7, 8]])

In [85]:
c=([8,9,3,6])

In [81]:
b.flatten()

array([1, 2, 3, 4, 1, 6, 7, 8])

In [89]:
c= np.array([(11,21,31,14,),(14,65,87,98)])
c

array([[11, 21, 31, 14],
       [14, 65, 87, 98]])

In [90]:

np.hstack((b,c))

array([[ 1,  2,  3,  4, 11, 21, 31, 14],
       [ 1,  6,  7,  8, 14, 65, 87, 98]])

In [94]:
np.vstack((b,c))

array([[ 1,  2,  3,  4],
       [ 1,  6,  7,  8],
       [11, 21, 31, 14],
       [14, 65, 87, 98]])

In [104]:
#split an array in 2rd array
np.hsplit(c,2)

[array([[11, 21],
        [14, 65]]), array([[31, 14],
        [87, 98]])]

In [101]:
np.vsplit(c,2)

[array([[11, 21, 31, 14]]), array([[14, 65, 87, 98]])]

In [106]:
from numpy import poly1d

In [107]:
#creating a polynomial
p=poly1d([1,4,5,7])
p

poly1d([1, 4, 5, 7])

In [110]:
#Vectorization of the function
def myfun(a):
    if a<0:
        return a**2
    else:
        return a/2
np.vectorize(myfun)

In [111]:
np.real(c)

array([[11, 21, 31, 14],
       [14, 65, 87, 98]])

In [113]:
from scipy import linalg, sparse

In [117]:
#creating matrix
A=np.matrix(np.random.random((2,2)))
A

matrix([[0.25609103, 0.87607343],
        [0.25522424, 0.66897505]])

In [119]:
B=np.asmatrix(b)
b

array([[1, 2, 3, 4],
       [1, 6, 7, 8]])

In [121]:
D=np.mat([[2,7,8],[7,9,4]])
D

matrix([[2, 7, 8],
        [7, 9, 4]])

In [127]:
C=np.mat(np.random.random((2,5)))
C

matrix([[0.14739038, 0.15847703, 0.09705624, 0.08419128, 0.73882511],
        [0.61750047, 0.31168816, 0.81148829, 0.90997156, 0.48709485]])

In [131]:
A

matrix([[0.25609103, 0.87607343],
        [0.25522424, 0.66897505]])

In [128]:
#INvesrse
A.I

matrix([[-12.79681892,  16.75840236],
        [  4.88218267,  -4.89876345]])

In [129]:
linalg.inv(A)

array([[-12.79681892,  16.75840236],
       [  4.88218267,  -4.89876345]])

In [130]:
A.T

matrix([[0.25609103, 0.25522424],
        [0.87607343, 0.66897505]])

In [132]:
A.H

matrix([[0.25609103, 0.25522424],
        [0.87607343, 0.66897505]])

In [134]:
np.add(A,A)

matrix([[0.51218206, 1.75214686],
        [0.51044848, 1.3379501 ]])

In [135]:
np.dot(A,A)

matrix([[0.28917779, 0.81042581],
        [0.23609929, 0.67112279]])

In [136]:
np.vdot(A,A)

matrix([[0.06558261]])